apiVersion: apps/v1
kind: Deployment
metadata:
  name: els-postgres
  labels:
    app: els-postgres
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 5  # Keep only last 5 ReplicaSets
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: els-postgres
  template:
    metadata:
      labels:
        app: els-postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: els-postgres
      volumes:
      - name: els-postgres
        persistentVolumeClaim:
          claimName: els-postgres-pvc
