apiVersion: v1
kind: Service
metadata:
  name: els-postgres
  labels:
    app: els-postgres
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5432
  selector:
    app: els-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: els-postgres-pvc
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
