apiVersion: v2
name: devops-system
description: Umbrella chart for DevOps System Level 3
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: client-chart
    version: 1.0.0
    repository: file://./client
  - name: strapi-chart
    version: 0.1.0
    repository: file://./server
  - name: postgres-chart
    version: 0.1.0
    repository: file://./postgres
