apiVersion: v2
name: els-devops-system
description: Umbrella chart for Level 4 deployment
type: application
version: 1.0.0
dependencies:
  - name: els-client
    version: "1.0.2"
    repository: "file://./client"
  - name: els-server
    version: "0.1.0"
    repository: "file://./server"
  - name: els-postgres
    version: "1.0.1"
    repository: "file://./postgres"
