apiVersion: v2
name: devops-system
description: Umbrella chart for Level 4 deployment
type: application
version: 1.0.0
dependencies:
  - name: client
    version: "1.0.0"
    repository: "file://./client"
  - name: server
    version: "0.1.0"
    repository: "file://./server"
  - name: postgres
    version: "1.0.0"
    repository: "file://./postgres"
