apiVersion: v2
name: devops-system
description: Umbrella chart for Level 4 deployment
type: application
version: 1.0.0
dependencies:
  - name: els-client
    version: "1.0.0"
    repository: "file://./client"
    alias: client
  - name: els-server
    version: "0.1.0"
    repository: "file://./server"
    alias: server
  - name: els-postgres
    version: "1.0.0"
    repository: "file://./postgres"
    alias: postgres
