apiVersion: v2
name: devops-system
description: Umbrella chart for Level 3 deployment
type: application
version: 1.0.0
dependencies:
  - name: els-client
    version: "1.0.0"
    repository: "file://./client"
  - name: els-server
    version: "0.1.0"
    repository: "file://./server"
  - name: els-postgres
    version: "1.0.0"
    repository: "file://./postgres"
