replicaCount: 1
fullnameOverride: els-postgres

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "17-alpine"

env:
  POSTGRES_DB: strapi
  POSTGRES_USER: strapi
  POSTGRES_PASSWORD: strapi

storage:
  size: 1Gi
  accessMode: ReadWriteOnce

service:
  type: ClusterIP
  port: 5432
