apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-server-monitor
  labels:
    app: devops-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
