apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client.fullname" . }}-config
  labels:
    {{- include "client.labels" . | nindent 4 }}
data:
  config.js: |
    window.env = {
      API_URL: "{{ .Values.config.apiUrl }}"
    };
