apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-client-monitor
  labels:
    app: devops-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: client
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
