apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: els-ingress
  namespace: devops-system
spec:
  ingressClassName: nginx
  rules:

  # ---------------------------
  # Backend (Strapi server)
  # ---------------------------
  - host: api.els.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server
            port:
              number: 1337

  # ---------------------------
  # Frontend (Client)
  # ---------------------------
  - host: app.els.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 80
