apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 967bb338b873a9ffec6eaa3fd2775d7f94eb11d9

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 967bb338b873a9ffec6eaa3fd2775d7f94eb11d9

