apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 1c56b73f2656c1659d075387b5d591052aaec41d

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 1c56b73f2656c1659d075387b5d591052aaec41d

