apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: f3be23bbd021f49c53dacabab778c2e8edcef815

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: f3be23bbd021f49c53dacabab778c2e8edcef815

