apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 1ba862086c871d94492d26b83bfa57a68928b234

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 1ba862086c871d94492d26b83bfa57a68928b234

