apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
<<<<<<< HEAD
  newName: YOUR_DOCKER_USERNAME/devops-client
  newTag: 45454f478ded7686213a94a05035446c4673d2fd

- name: devops-server-image
  newName: YOUR_DOCKER_USERNAME/devops-server
  newTag: 45454f478ded7686213a94a05035446c4673d2fd
=======
  newName: dhruvre/devops-client  # ⚠️ Auto-updated by CI
  newTag: 45454f478ded7686213a94a05035446c4673d2fd

- name: devops-server-image
  newName: dhruvre/devops-server  # ⚠️ Auto-updated by CI
  newTag: 45454f478ded7686213a94a05035446c4673d2fd
>>>>>>> a5c095c (feat: level 2 test final)

