apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: da287edc75d3f400419a5db49c36c756609d215c

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: da287edc75d3f400419a5db49c36c756609d215c

