apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client  # ⚠️ Auto-updated by CI
  newTag: 64a30ee2544f93109e83aaf2ea13829905f99342

- name: devops-server-image
  newName: dhruvre/devops-server  # ⚠️ Auto-updated by CI
  newTag: 64a30ee2544f93109e83aaf2ea13829905f99342
