apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 5559f39350ffab269f2aa1ba698de11327368271

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 5559f39350ffab269f2aa1ba698de11327368271

