apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 0277d7b862c5f855974792cbb1f993bfc275a729

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 0277d7b862c5f855974792cbb1f993bfc275a729

