apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 9c83821a96e2b8adeb7fe371ce40cc45a39a7903

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 9c83821a96e2b8adeb7fe371ce40cc45a39a7903

