apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 3fd4d8d4b4b95fc9aa2b8c9c0fd3c8eb590cb77b

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 3fd4d8d4b4b95fc9aa2b8c9c0fd3c8eb590cb77b

