apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 2ba0af76392fede008259cc4329fc44f3f375197

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 2ba0af76392fede008259cc4329fc44f3f375197

