apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: ed64bdb63cedb220acab3f491a6b121127e172d5

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: ed64bdb63cedb220acab3f491a6b121127e172d5

