apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
  newName: ${DOCKER_USERNAME}/devops-client  # ⚠️ Auto-updated by CI
  newTag: latest # Auto-updated by CI with git commit SHA

- name: devops-server-image
  newName: ${DOCKER_USERNAME}/devops-server  # ⚠️ Auto-updated by CI
  newTag: latest # Auto-updated by CI with git commit SHA
