apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 29c6a2b030ab99d61d0fbcbc7879bb372d3896a4

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 29c6a2b030ab99d61d0fbcbc7879bb372d3896a4
