apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 833ce12a77f5e6f80f90d63a81a91f0c5f46b6bd

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 833ce12a77f5e6f80f90d63a81a91f0c5f46b6bd

