apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 2ff7730afdbb7842e8386bb50b2a28cfbc17a557

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 2ff7730afdbb7842e8386bb50b2a28cfbc17a557

