apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: e4419dc2026e71e7f3ee67d05e2fd9f7a47e9639

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: e4419dc2026e71e7f3ee67d05e2fd9f7a47e9639

