apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: eefc74027fc8ea56a1c342a7e0cdc602ed5cae73

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: eefc74027fc8ea56a1c342a7e0cdc602ed5cae73

