apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: d45bceaf762f37039f56d562dfbec38ea536e4a5

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: d45bceaf762f37039f56d562dfbec38ea536e4a5

