apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 83c07e09fc2fca6e425d2231ed5ef0662438c1d4

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 83c07e09fc2fca6e425d2231ed5ef0662438c1d4

