apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 42a8170eddbbed0f58a53743084c16caa835fb4b

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 42a8170eddbbed0f58a53743084c16caa835fb4b

