apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 9c7fb272e97e172bb013a370ef2f724982f04343

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 9c7fb272e97e172bb013a370ef2f724982f04343

