apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 72c364fe8dee706b23acc2424e26f779ee9b595c

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 72c364fe8dee706b23acc2424e26f779ee9b595c

