apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 3109216238add1a685e5138788a793e9ca77bf02

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 3109216238add1a685e5138788a793e9ca77bf02

