apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 3ac7a04847c79831fe13192aabe303d8538999da

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 3ac7a04847c79831fe13192aabe303d8538999da

