apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 4f9d638ff63408548e6f6086a3dfe766811f7ecb

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 4f9d638ff63408548e6f6086a3dfe766811f7ecb

