apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 407a01cf1d71d5aed2b56d5af8d49de3a1c44915

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 407a01cf1d71d5aed2b56d5af8d49de3a1c44915

