apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml
- client-configmap.yaml

images:
- name: devops-client-image
  newName: dhruvre/devops-client
  newTag: 16b65efa01ee64ce6bd95a197dcc16247a6a0cd9

- name: devops-server-image
  newName: dhruvre/devops-server
  newTag: 16b65efa01ee64ce6bd95a197dcc16247a6a0cd9

