apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: devops-client-image
<<<<<<< HEAD
  newName: YOUR_DOCKER_USERNAME/devops-client
  newTag: b7eeeb062534228727c7995e68c66e3b055ffd29

- name: devops-server-image
  newName: YOUR_DOCKER_USERNAME/devops-server
  newTag: b7eeeb062534228727c7995e68c66e3b055ffd29
=======
  newName: dhruvre/devops-client  # ⚠️ Auto-updated by CI
  newTag: b7eeeb062534228727c7995e68c66e3b055ffd29

- name: devops-server-image
  newName: dhruvre/devops-server  # ⚠️ Auto-updated by CI
  newTag: b7eeeb062534228727c7995e68c66e3b055ffd29
>>>>>>> a5c095c (feat: level 2 test final)

